"""add github_access_token to repositories

Revision ID: f97d64bed461
Revises: a2c4c225b2d9
Create Date: 2026-07-13 18:03:43.832557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f97d64bed461'
down_revision: Union[str, Sequence[str], None] = 'a2c4c225b2d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('github_access_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'github_access_token')
    # ### end Alembic commands ###
